sudo apt-get update;
sudo apt-get upgrade;
sudo apt remove apport apport-gtk;
sudo apt install ubuntu-restricted-addons;
sudo apt install gdebi;
sudo apt-get install ubuntu-restricted-extras;
sudo apt install build-essential;
sudo apt install clang;
sudo apt install codeblocks;
sudo apt install uget;
sudo apt install git;
sudo apt install python-is-python3;
sudo apt install python3-pip;
echo "alias pip=pip3" >> ~/.bash_aliases;
source ~/.bash_aliases;
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb;
sudo apt install ./google-chrome-stable_current_amd64.deb;
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg;
sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/;
sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list';
sudo apt-get install apt-transport-https;
sudo apt-get update;
sudo apt-get install code;